# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QPixmap, QIcon
from PyQt5.QtWidgets import QFileDialog, QMessageBox

from movie_database import MovieDatabase
from res_owner import ResourceOwner

db = MovieDatabase()


class MovieDetailForm(QtWidgets.QWidget):
    def __init__(self, movie, parent):
        super().__init__()
        self.movie = movie
        self.parent = parent
        self.setupUi()
        self.image_path = None

    def setupUi(self):
        self.setObjectName("MovieDetailForm")
        self.resize(600, 560)
        self.setWindowIcon(QIcon(ResourceOwner.icon))
        self.formLayoutWidget = QtWidgets.QWidget(self)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 310, 601, 170))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(8, 8, 8, 8)
        self.formLayout.setObjectName("formLayout")
        self.label_title = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_title.setObjectName("label_title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_title)
        self.lineEdit_title = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_title.setObjectName("lineEditTitle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_title)
        self.label_created_date = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_created_date.setObjectName("label_created_date")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_created_date)
        self.lineEdit_year = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_year.setObjectName("lineEditYear")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_year)
        self.country = QtWidgets.QLabel(self.formLayoutWidget)
        self.country.setObjectName("country")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.country)
        self.lineEdit_country = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_country.setObjectName("lineEditCountry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_country)
        self.rating = QtWidgets.QLabel(self.formLayoutWidget)
        self.rating.setObjectName("rating")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.rating)
        self.lineEdit_rating = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_rating.setObjectName("lineEditRating")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_rating)
        self.labelGenre = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelGenre.setObjectName("labelGenre")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelGenre)
        self.comboBoxGenre = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBoxGenre.setObjectName("comboBoxGenre")
        self.comboBoxGenre.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBoxGenre)
        self.labelType = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelType.setObjectName("labelType")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelType)
        self.comboBoxType = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBoxType.setObjectName("comboBoxType")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBoxType)
        self.pushButtonImage = QtWidgets.QPushButton(self)
        self.pushButtonImage.setGeometry(QtCore.QRect(30, 280, 161, 23))
        self.pushButtonImage.setObjectName("pushButtonImage")
        self.labelImage = QtWidgets.QLabel(self)
        self.labelImage.setGeometry(QtCore.QRect(250, 0, 131, 300))
        self.labelImage.setObjectName("labelImage")

        self.pushButtonSave = QtWidgets.QPushButton(self)
        self.pushButtonSave.setGeometry(250, 490, 130, 50)
        self.pushButtonSave.setText("Сохранить")
        self.pushButtonSave.setStyleSheet("font-weight: bold")
        self.pushButtonSave.clicked.connect(self.update_movie)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.pushButtonImage.clicked.connect(self.set_image)
        self.pushButtonSave.clicked.connect(self.update_movie)

    def update_movie(self):
        self.movie.title_ru = self.lineEdit_title.text()
        self.movie.created_date = self.lineEdit_year.text()
        rating = self.lineEdit_rating.text()
        try:
            rating = float(rating)
            self.movie.rating = rating
        except ValueError as e:
            msg = QMessageBox(self)
            msg.setWindowTitle("Ошибка")
            msg.setText("Рейтинг должен быть числом!")
            msg.show()
            return

        if self.image_path is not None:
            self.movie.image_path = self.image_path

        self.movie.genres = self.comboBoxGenre.currentText()
        self.movie.movie_type = self.comboBoxType.currentText()
        self.movie.country = self.lineEdit_country.text()
        self.parent.updateItem(self.movie)
        self.close()

    def fill_combobox_genres(self):
        genres_list = db.get_genres_list()
        if len(genres_list) > 0:
            for i in db.get_genres_list():
                self.comboBoxGenre.addItem(i[1])

    def fill_combobox_type(self):
        type_list = db.get_movie_type()
        if len(type_list) > 0:
            for i in db.get_movie_type():
                self.comboBoxType.addItem(i[1])

    def set_image(self):
        owner = ResourceOwner()
        image_dialog = QFileDialog.getOpenFileName(self, "Выберите обложку", "", filter="*.jpg *.png")
        if image_dialog[0] != '':
            self.image_path = owner.copy_image_to_dir(image_dialog[0])
            pixmap = QPixmap(self.image_path)
            self.labelImage.setPixmap(pixmap)
        else:
            return

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MovieDetailForm", self.movie.title_ru))
        self.label_title.setText(_translate("MovieDetailForm", "Название"))
        self.label_created_date.setText(_translate("MovieDetailForm", "Год выпуска"))
        self.country.setText(_translate("MovieDetailForm", "Страна производства"))
        self.rating.setText(_translate("MovieDetailForm", "Рейтинг"))
        self.labelGenre.setText(_translate("MovieDetailForm", "Жанр"))
        self.comboBoxGenre.setItemText(0, _translate("MovieDetailForm", self.movie.genres))
        self.labelType.setText(_translate("MovieDetailForm", "Тип"))
        self.pushButtonImage.setText(_translate("MovieDetailForm", "Изменить постер"))
        self.labelImage.setText(_translate("MovieDetailForm", "TextLabel"))
        pixmap = QPixmap(self.movie.image_path)
        self.labelImage.setPixmap(pixmap)
        self.lineEdit_title.setText(self.movie.title_ru)
        self.lineEdit_year.setText(str(self.movie.created_date))
        self.lineEdit_country.setText(self.movie.country)
        self.lineEdit_rating.setText(str(self.movie.rating))
        self.fill_combobox_genres()
        self.fill_combobox_type()
