# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movie_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MovieDetailForm(QtWidgets.QWidget):
    def __init__(self, movie):
        super().__init__()
        self.movie = movie

    def setupUi(self):
        self.setObjectName("MovieDetailForm")
        self.resize(600, 560)
        self.formLayoutWidget = QtWidgets.QWidget(self)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 310, 601, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(8, 8, 8, 8)
        self.formLayout.setObjectName("formLayout")
        self.label_title = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_title.setObjectName("label_title")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_title)
        self.lineEditTitle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditTitle.setObjectName("lineEditTitle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditTitle)
        self.label_created_date = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_created_date.setObjectName("label_created_date")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_created_date)
        self.lineEditYear = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditYear.setObjectName("lineEditYear")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditYear)
        self.country = QtWidgets.QLabel(self.formLayoutWidget)
        self.country.setObjectName("country")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.country)
        self.lineEditCountry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditCountry.setObjectName("lineEditCountry")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditCountry)
        self.rating = QtWidgets.QLabel(self.formLayoutWidget)
        self.rating.setObjectName("rating")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.rating)
        self.lineEditRating = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditRating.setObjectName("lineEditRating")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditRating)
        self.labelGenre = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelGenre.setObjectName("labelGenre")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelGenre)
        self.comboBoxGenre = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBoxGenre.setObjectName("comboBoxGenre")
        self.comboBoxGenre.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBoxGenre)
        self.labelType = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelType.setObjectName("labelType")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelType)
        self.comboBoxType = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBoxType.setObjectName("comboBoxType")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBoxType)
        self.pushButtonImage = QtWidgets.QPushButton(self)
        self.pushButtonImage.setGeometry(QtCore.QRect(30, 280, 161, 23))
        self.pushButtonImage.setObjectName("pushButtonImage")
        self.labelImage = QtWidgets.QLabel(self)
        self.labelImage.setGeometry(QtCore.QRect(250, 0, 131, 300))
        self.labelImage.setObjectName("labelImage")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MovieDetailForm", self.movie.title_ru))
        self.label_title.setText(_translate("MovieDetailForm", "Название"))
        self.label_created_date.setText(_translate("MovieDetailForm", "Год выпуска"))
        self.country.setText(_translate("MovieDetailForm", "Страна производства"))
        self.rating.setText(_translate("MovieDetailForm", "Рейтинг"))
        self.labelGenre.setText(_translate("MovieDetailForm", "Жанр"))
        self.comboBoxGenre.setItemText(0, _translate("MovieDetailForm", "New Item"))
        self.labelType.setText(_translate("MovieDetailForm", "Тип"))
        self.pushButtonImage.setText(_translate("MovieDetailForm", "Изменить постер"))
        self.labelImage.setText(_translate("MovieDetailForm", "TextLabel"))
